# Example sources configuration for the Johtava Arkkitehti Podcast agent
# Add or modify sources as needed. Supported types: rss, http

sources:

- name: V01.io
  type: rss
  url: https://www.v01.io/posts/index.xml
  keywords: [ "technology", "software development", "blog" ]
  category_hints: [ "Architecture/Infra", "DevOps" ]

- name: Richard Seroter's Blog
  type: rss
  url: https://seroter.com/feed/
  keywords: [ "architecture", "cloud", "devops", "ai", "leadership" ]
  category_hints: [ "Architecture/Infra", "Leadership", "DevOps" ]

- name: DZone Agile
  type: rss
  url: https://feeds.dzone.com/agile
  keywords: [ "agile", "scrum", "devops", "project management" ]
  category_hints: [ "Agile", "Leadership" ]

- name: DZone Team Management
  type: rss
  url: https://feeds.dzone.com/team-management
  keywords: [ "leadership", "management", "agile", "productivity" ]
  category_hints: [ "Leadership" ]

- name: DZone DevOps
  type: rss
  url: https://feeds.dzone.com/devops-and-cicd
  keywords: [ "devops", "cicd", "kubernetes", "docker", "automation" ]
  category_hints: [ "DevOps", "Architecture/Infra" ]

- name: DZone Methodologies
  type: rss
  url: https://feeds.dzone.com/methodologies
  keywords: [ "agile", "scrum", "devops", "architecture", "bdd" ]
  category_hints: [ "Agile", "Architecture/Infra" ]

- name: The Pragmatic Engineer
  type: rss
  url: https://blog.pragmaticengineer.com/rss/
  keywords: [ "engineering", "leadership", "big tech", "career" ]
  category_hints: [ "Leadership", "Architecture/Infra" ]

# Agile – high-authority sources
- name: Agile Alliance
  type: rss
  url: https://www.agilealliance.org/feed/
  keywords: [ "agile", "scrum", "kanban", "lean", "retrospective", "coaching" ]
  category_hints: [ "Agile", "Leadership" ]

- name: Scrum.org Blog
  type: rss
  url: https://www.scrum.org/resources/blog/feed
  keywords: [ "scrum", "product owner", "sprint", "retrospective", "scrum master" ]
  category_hints: [ "Agile" ]

- name: Mountain Goat Software
  type: rss
  url: https://www.mountaingoatsoftware.com/blog/rss
  keywords: [ "agile", "user stories", "planning", "estimation", "scrum" ]
  category_hints: [ "Agile" ]

# DevOps – high-authority sources
- name: Kubernetes Blog
  type: rss
  url: https://kubernetes.io/feed.xml
  keywords: [ "kubernetes", "containers", "cncf", "cluster", "k8s" ]
  category_hints: [ "DevOps", "Architecture/Infra" ]

- name: Docker Blog
  type: rss
  url: https://www.docker.com/blog/feed/
  keywords: [ "docker", "containers", "build", "compose", "supply chain" ]
  category_hints: [ "DevOps" ]

- name: GitLab Blog
  type: rss
  url: https://about.gitlab.com/blog/feed.xml
  keywords: [ "gitlab", "cicd", "devsecops", "pipelines", "ai" ]
  category_hints: [ "DevOps" ]

- name: HashiCorp Blog
  type: rss
  url: https://www.hashicorp.com/blog/feed.xml
  keywords: [ "terraform", "vault", "consul", "nomad", "iac" ]
  category_hints: [ "DevOps", "Architecture/Infra" ]
